// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: proto/filelist.proto

package filelist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListFilesRequest specifies the directory to list.
type ListFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path is the root directory to list files from.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// max_depth limits recursion depth. 0 means unlimited.
	MaxDepth      int32 `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_proto_filelist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filelist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_filelist_proto_rawDescGZIP(), []int{0}
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListFilesRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

// ListFilesResponse contains the file listing.
type ListFilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// root is the requested directory path.
	Root string `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// files is the list of files and directories.
	Files []*FileInfo `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	// total_count is the total number of entries returned.
	TotalCount    int64 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_proto_filelist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filelist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_filelist_proto_rawDescGZIP(), []int{1}
}

func (x *ListFilesResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// FileInfo describes a single file or directory.
type FileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path is the full path relative to the root.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// name is the base name of the file.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// size is the file size in bytes (0 for directories).
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// mode is the file permission mode (unix style).
	Mode uint32 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	// mod_time is the modification time as Unix timestamp (seconds).
	ModTime int64 `protobuf:"varint,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	// is_dir indicates if this entry is a directory.
	IsDir         bool `protobuf:"varint,6,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_filelist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filelist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_filelist_proto_rawDescGZIP(), []int{2}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

var File_proto_filelist_proto protoreflect.FileDescriptor

const file_proto_filelist_proto_rawDesc = "" +
	"\n" +
	"\x14proto/filelist.proto\x12\bfilelist\"C\n" +
	"\x10ListFilesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepth\"r\n" +
	"\x11ListFilesResponse\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12(\n" +
	"\x05files\x18\x02 \x03(\v2\x12.filelist.FileInfoR\x05files\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\"\x8c\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x19\n" +
	"\bmod_time\x18\x05 \x01(\x03R\amodTime\x12\x15\n" +
	"\x06is_dir\x18\x06 \x01(\bR\x05isDir2W\n" +
	"\x0fFileListService\x12D\n" +
	"\tListFiles\x12\x1a.filelist.ListFilesRequest\x1a\x1b.filelist.ListFilesResponseB0Z.github.com/paulstuart/zstd-dict/proto/filelistb\x06proto3"

var (
	file_proto_filelist_proto_rawDescOnce sync.Once
	file_proto_filelist_proto_rawDescData []byte
)

func file_proto_filelist_proto_rawDescGZIP() []byte {
	file_proto_filelist_proto_rawDescOnce.Do(func() {
		file_proto_filelist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_filelist_proto_rawDesc), len(file_proto_filelist_proto_rawDesc)))
	})
	return file_proto_filelist_proto_rawDescData
}

var file_proto_filelist_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_filelist_proto_goTypes = []any{
	(*ListFilesRequest)(nil),  // 0: filelist.ListFilesRequest
	(*ListFilesResponse)(nil), // 1: filelist.ListFilesResponse
	(*FileInfo)(nil),          // 2: filelist.FileInfo
}
var file_proto_filelist_proto_depIdxs = []int32{
	2, // 0: filelist.ListFilesResponse.files:type_name -> filelist.FileInfo
	0, // 1: filelist.FileListService.ListFiles:input_type -> filelist.ListFilesRequest
	1, // 2: filelist.FileListService.ListFiles:output_type -> filelist.ListFilesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_filelist_proto_init() }
func file_proto_filelist_proto_init() {
	if File_proto_filelist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_filelist_proto_rawDesc), len(file_proto_filelist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_filelist_proto_goTypes,
		DependencyIndexes: file_proto_filelist_proto_depIdxs,
		MessageInfos:      file_proto_filelist_proto_msgTypes,
	}.Build()
	File_proto_filelist_proto = out.File
	file_proto_filelist_proto_goTypes = nil
	file_proto_filelist_proto_depIdxs = nil
}
