// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: proto/filelist.proto

package filelist

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileListService_ListFiles_FullMethodName = "/filelist.FileListService/ListFiles"
)

// FileListServiceClient is the client API for FileListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FileListService provides directory listing operations.
type FileListServiceClient interface {
	// ListFiles returns a recursive listing of files in the specified directory.
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
}

type fileListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileListServiceClient(cc grpc.ClientConnInterface) FileListServiceClient {
	return &fileListServiceClient{cc}
}

func (c *fileListServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, FileListService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileListServiceServer is the server API for FileListService service.
// All implementations must embed UnimplementedFileListServiceServer
// for forward compatibility.
//
// FileListService provides directory listing operations.
type FileListServiceServer interface {
	// ListFiles returns a recursive listing of files in the specified directory.
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	mustEmbedUnimplementedFileListServiceServer()
}

// UnimplementedFileListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileListServiceServer struct{}

func (UnimplementedFileListServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedFileListServiceServer) mustEmbedUnimplementedFileListServiceServer() {}
func (UnimplementedFileListServiceServer) testEmbeddedByValue()                         {}

// UnsafeFileListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileListServiceServer will
// result in compilation errors.
type UnsafeFileListServiceServer interface {
	mustEmbedUnimplementedFileListServiceServer()
}

func RegisterFileListServiceServer(s grpc.ServiceRegistrar, srv FileListServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileListService_ServiceDesc, srv)
}

func _FileListService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileListServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileListService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileListServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileListService_ServiceDesc is the grpc.ServiceDesc for FileListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filelist.FileListService",
	HandlerType: (*FileListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFiles",
			Handler:    _FileListService_ListFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/filelist.proto",
}
